language:python
python:
    - "3.6"
install:
    - pip install -e .
    - pip install pytest-cov codecov

script:
    - pytest --cov=src tests
<<<<<<< HEAD
=======
 
after_success:
    - codecov
>>>>>>> 604b1f287ecff5c7ec1709ad382b531af80c2b13
